# use this file for encrypted user/password information.
# Unencrypted values may be used in this file using standard yaml syntax
# Encrypted values must be enclosed in ![] within the quotes.
# Listener configuration
case-listener:
   http-client:
      client-id: "![DaPFpmc6y6I=]"
      client-secret: "![sgi/h//FjVg=]"
anypoint-mq:
  client-id:  "![idlKsdgbddNP21JRDMZlLH7yt4Rz79Eu/9tVSxxWzqf+HIvvraMF3A==]"
  client-secret: "![rqyenApMNzzRa2tauiqQM8HinSLU4eL3e0Fsxhpy/wa7D3Kgvp0a0g==]"
      
            